global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'evoting-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'evoting-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'EVoting Backend'
          environment: 'development'
          instance: 'evoting-backend-1'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'Prometheus'
          environment: 'monitoring'

  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
        labels:
          application: 'Grafana'
          environment: 'monitoring'